# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broken_product', to='issues.Product'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tech_guy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
