# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20170817_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tech_guy',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
