# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20170817_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='is_solved',
        ),
        migrations.AddField(
            model_name='issue',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='customer_surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('QU', 'IN QUEUE'), ('FI', 'FIXING'), ('DO', 'DONE')], default='QU', max_length=2),
        ),
    ]
