# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20170819_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1, null=True)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='customer_surname',
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(default='def', max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='broken_product', to='issues.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='tech_guy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='issues.Customer'),
            preserve_default=False,
        ),
    ]
