# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20170819_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tech_guy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
