# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_customer_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
