# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20170819_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='done_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='todo_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
