# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20170819_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='price',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
