# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_issue_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='case_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'KIRMIZI'), ('green', 'YEŞİL'), ('blue', 'MAVİ'), ('white', 'BEYAZ'), ('black', 'SİYAH'), ('brown', 'KAHVERENGİ'), ('purple', 'MOR'), ('orange', 'TURUNCU')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.BooleanField(default=False),
        ),
    ]
