# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0012_auto_20170820_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
