# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_issue_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('QU', 'IN QUEUE'), ('FI', 'FIXING'), ('RE', 'RETURN'), ('CE', 'COMPONENTS EXPECTED'), ('DO', 'DONE')], default='QU', max_length=2),
        ),
    ]
